version: '3'

services:
    db:
        image: mysql:latest
        container_name: ${PROJECT_NAME}_db
        volumes:
            - ${PROJECT_PATH}/db:/var/lib/mysql
            - ${PROJECT_PATH}/api/db_schema:/db_schema
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
        networks:
          digitalabs:
            ipv4_address: ${PROJECT_NETWORK}.2
    wordpress:
        image: wordpress:latest
        container_name: ${PROJECT_NAME}_wp
        ports:
          - 8080:80
        environment:
          - MODE=dev
        volumes:
          # - ${PROJECT_PATH}/uploads/:/uploads
          - ${PROJECT_PATH}/wordpress:/var/www/html
          - ${PROJECT_PATH}/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
          # - ./php/ssmtp.conf:/etc/ssmtp/ssmtp.conf:ro
          # - ./php/php-mail.conf:/usr/local/etc/php/conf.d/mail.ini:ro
          # - ./php/path.conf:/etc/ssmtp/revaliases:ro
        networks:
          digitalabs:
            ipv4_address: ${PROJECT_NETWORK}.4
networks:
  digitalabs:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${PROJECT_NETWORK}.0/24